// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiGuideService.Data;

namespace WebApiDataService.Migrations
{
    [DbContext(typeof(AppDBContent))]
    [Migration("20200920114547_DataInit")]
    partial class DataInit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApiDataService.Data.Models.DataIntersection", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Intersection")
                        .HasColumnType("int");

                    b.Property<int>("Objectindex")
                        .HasColumnType("int");

                    b.Property<int>("Versionindex")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("dataIntersection");
                });
#pragma warning restore 612, 618
        }
    }
}
